config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :paintings
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'paintings#index'

  match 'about', to: 'store#about', via: :get
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/painting.rb
# frozen_string_literal: true

class Painting < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :line_items

  mount_uploader :image, ImageUploader
  # serialize :image, JSON # If you use SQLite, add this line

  validates :title, :description, :price, presence: true
  validates :description, length: { maximum: 1000, too_long: '%<count>s characters is the maximum allowed.' }
  validates :title, length: { maximum: 140, too_long: '%<count>s characters is the maximum allowed.' }
  validates :price, numericality: { max_digits: 7 }

  private

  def not_referenced_by_any_line_item
    return if line_items.empty?

    errors.add(:base, 'Line items present')
    throw :abort
  end
end

app/controllers/paintings_controller.rb
# frozen_string_literal: true

class PaintingsController < ApplicationController
  before_action :set_painting, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  before_action :correct_user, only: %i[new edit update destroy]

  # GET /paintings or /paintings.json
  def index
    @paintings = Painting.all.order('created_at DESC')
  end

  # GET /paintings/1 or /paintings/1.json
  def show; end

  # GET /paintings/new
  def new
    @painting = current_user.paintings.build
  end

  # GET /paintings/1/edit
  def edit; end

  # POST /paintings or /paintings.json
  def create
    @painting = current_user.paintings.build(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to painting_url(@painting), notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1 or /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to painting_url(@painting), notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1 or /paintings/1.json
  def destroy
    @painting.destroy

    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def correct_user
    @check_point = current_user.paintings.find_by(user_id: 1) || current_user.id == 1
    redirect_to paintings_path, notice: 'Not Authorized To Do This!' if @check_point.nil?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_painting
    @painting = Painting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def painting_params
    params.require(:painting).permit(:title, :description, :price, :size, :marerials, :image)
  end
end

app/helpers/paintings_helper.rb
# frozen_string_literal: true

module PaintingsHelper
  def painting_author(painting)
    user_signed_in? && current_user.id == painting.user_id
  end
end

app/views/paintings/_form.html.erb
<%= simple_form_for(@painting, html: { multipart: true }
) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :title, required: true, input_html: {class: "input"}, wrapper: false %>
    <%= f.input :size, required: true, input_html: {class: "input"}, wrapper: false %>
    <%= f.input :materials, required: true, input_html: {class: "input"}, wrapper: false %>
    <%= f.input :description, required: true, input_html: {class: "textarea"}, wrapper: false
 %>
    <%= f.input :price, required: true, input_html: {class: "input", maxlenghth: 7}, wrapper: false
 %>
    <%= f.input :image, as: :file, input_html: { class:"file-input painting-image" }, wrapper: false %>
  </div>
  <output id="list"></output>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-outline-warning" %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div id="<%= dom_id painting %>">
  <p>
    <strong>Title:</strong>
    <%= painting.title %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= painting.description %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= number_to_currency(painting.price) %>
  </p>
  <p>
    <%= link_to image_tag(painting.image_url(:thumb)), painting %>
  </p>
  <% if painting_author(painting) %>
    <div class="d-flex mt-3">
      <%= link_to 'Edit', edit_painting_path(painting), class: "btn btn-outline-warning btn-sm me-1" %>
      <%= button_to "Delete", painting, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class:'btn btn-outline-danger btn-sm' %>
    </div>
  <% end %>
</div>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>
<%= render "form", painting: @painting %>
<br>
<div>
  <%= link_to "Show this painting", @painting, class:'btn btn-outline-secondary' %> |
  <%= link_to "Back to paintings", paintings_path, class:'btn btn-outline-secondary' %>
</div>

app/views/paintings/index.html.erb
<div id="paintings" class='mb-5'>
  <div class="painting-index-grid pt-4">
    <% @paintings.each do |painting| %>
      <div class="painting">
        <div class="painting-thumb">
          <%= link_to image_tag(painting.image_url(:thumb)), painting, class: 'painting-image' %>
        </div>
        <div class="p-3">
          <h3 class="fw-bold fs-4 title"><%= painting.title %></h3>
          <p class="fs-3 fw-bold pt-2 price"><%= number_to_currency(painting.price) %></p>
          <% if painting_author(painting) %>
            <div class="d-flex mt-3">
              <%= link_to 'Edit', edit_painting_path(painting), class: "btn btn-outline-warning btn-sm me-1" %>
              <%= button_to "Delete", painting, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class:'btn btn-outline-danger btn-sm' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render "form", painting: @painting %>

<br>

<div>
  <%= link_to "Back to paintings", paintings_path %>
</div>

app/views/paintings/show.html.erb
<section class="section painting-show">
  <div>
    <div class="feature-image mt-5">
      <%= image_tag(@painting.image_url(:default)) %>
    </div>
    <h1 class="title my-5"><%= @painting.title %></h1>
    <div class="content p-4 mt-3 bg-white">
      <h3 class="subtitle">Description</h3>
      <%= @painting.description %>
      <h5 class="subtitle mt-2">Materials</h5>
      <%= @painting.materials %>
      <h5 class="subtitle mt-2">Size</h5>
      <%= @painting.size %>
    </div>
  </div>
  <div>
    <div class="bg-white p-4">
      <h4 class="title text-end mb4"><%= number_to_currency(@painting.price) %></h4>
      <% if current_user.nil?%>
        <%= button_to 'Plese Login before adding an item to the cart', user_session_path, class: 'btn btn-outline-success add-to-cart' %>
      <% else %>
        <%= button_to 'Add to cart', line_items_path(painting_id: @painting), class: 'btn btn-outline-success add-to-cart' %>
      <% end %>
    </div>
  </div>
  <% if painting_author(@painting) %>
    <div class="d-flex mt-3">
      <%= link_to 'Edit', edit_painting_path(@painting), class: 'btn btn-outline-warning btn-sm me-2' %>
      <%= button_to "Delete", @painting, form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete, class:'btn btn-outline-danger btn-sm' %>
    </div>
  <% end %>
  <%= link_to "Back to paintings", paintings_path, class:'btn btn-outline-secondary btn-sm mt-2 mb-5' %>
</section>