config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :paintings
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'paintings#index'

  match 'about', to: 'store#about', via: :get
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag 'logo.jpg', alt: 'My Brand Logo', class:"navbar-brand mt-5"%>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', alt: 'My Brand Logo', class:"navbar-brand offcanvas-title", id:"offcanvasNavbarLabel" %>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" id="offcanvas-close-btn" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav flex-grow-1 pe-3 fs-5">
          <li class="nav-item"> <%= link_to 'About Me', about_path, class:"nav-link btn btn-info m-2 px-2" %> </li>
          <li><%= link_to 'Paintings', paintings_path, class:"nav-link btn btn-info m-2 px-2" %></li>
          <%# check point for correct user %>
          <% if user_signed_in? && current_user.id == 1  %>
            <li class="nav-item"> <%= link_to 'Add Paining', new_painting_path, class:"nav-link btn btn-info m-2 px-2"%> </li>
          <% end %>
          <ul class="navbar-nav fs-5 ms-auto">
            <%# switcher of buttons %>
            <% if user_signed_in? %>
              <li class="nav-item"> <%= link_to edit_user_registration_path, class:"nav-link btn btn-info m-2 px-2" do%>
                  <%= current_user.name %> <i class="bi bi-person-circle"></i>
                <% end %> </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link btn btn-info m-2 px-2"  do %>
                  Sign Out <i class="bi bi-box-arrow-right"></i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item"> <%= link_to new_user_session_path, class:"nav-link btn btn-info m-2 px-2" do %> Sign In <i class="bi bi-box-arrow-in-right"></i>
                <% end %>
              </li>
              <li class="nav-item"> <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link btn btn-info m-2 px-2" %>
              </li>
            <% end %>
            <%# check point for the cart -- inside aplication_helpers%>
            <% @total = total_cart_items %>
            <% if @total %>
              <%= link_to cart_path(@cart), class:"nav-link btn btn-info position-relative m-2 px-2" do %>
                Cart <i class="bi bi-cart2"></i> <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary fs-6"><%= @total %><span class="visually-hidden"></span></span>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <br>
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <%end%>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>